namenode:
  image: awesomedata/hadoop-namenode
  hostname: namenode
  container_name: namenode
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/namenode:/hadoop/dfs/name
  environment:
    - CLUSTER_NAME=test
  env_file:
    - ./hadoop.env
  ports:
    - "50070:50070"

datanode1:
  image: awesomedata/hadoop-datanode
  hostname: datanode1
  container_name: datanode1
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode1:/hadoop/dfs/data
  env_file:
    - ./hadoop.env

datanode2:
  image: awesomedata/hadoop-datanode
  hostname: datanode2
  container_name: datanode2
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode2:/hadoop/dfs/data
  env_file:
    - ./hadoop.env

datanode3:
  image: awesomedata/hadoop-datanode
  hostname: datanode3
  container_name: datanode3
  domainname: hadoop
  net: hadoop
  volumes:
    - ./data/datanode3:/hadoop/dfs/data
  env_file:
    - ./hadoop.env

spark-master:
  image: awesomedata/hadoop-spark-master
  hostname: spark-master
  container_name: spark-master
  domainname: hadoop
  net: hadoop
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode.hadoop:8020
    - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager.hadoop
    - SPARK_CONF_spark_eventLog_enabled=true
    - SPARK_CONF_spark_eventLog_dir=hdfs://namenode.hadoop:8020/spark-logs
    - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode.hadoop:8020/spark-logs
  env_file:
    - ./hadoop.env
  ports:
      - "8080:8080"

spark-worker1:
  image: awesomedata/hadoop-spark-worker
  hostname: spark-worker1
  container_name: spark-worker1
  domainname: hadoop
  net: hadoop
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode.hadoop:8020
    - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager.hadoop
    - SPARK_CONF_spark_eventLog_enabled=true
    - SPARK_CONF_spark_eventLog_dir=hdfs://namenode.hadoop:8020/spark-logs
    - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode.hadoop:8020/spark-logs
    - SPARK_MASTER_URL=spark://spark-master.hadoop:7077
  env_file:
    - ./hadoop.env

spark-worker2:
  image: awesomedata/hadoop-spark-worker
  hostname: spark-worker2
  container_name: spark-worker2
  domainname: hadoop
  net: hadoop
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode.hadoop:8020
    - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager.hadoop
    - SPARK_CONF_spark_eventLog_enabled=true
    - SPARK_CONF_spark_eventLog_dir=hdfs://namenode.hadoop:8020/spark-logs
    - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode.hadoop:8020/spark-logs
    - SPARK_MASTER_URL=spark://spark-master.hadoop:7077
  env_file:
    - ./hadoop.env

spark-worker3:
  image: awesomedata/hadoop-spark-worker
  hostname: spark-worker3
  container_name: spark-worker3
  domainname: hadoop
  net: hadoop
  environment:
    - CORE_CONF_fs_defaultFS=hdfs://namenode.hadoop:8020
    - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager.hadoop
    - SPARK_CONF_spark_eventLog_enabled=true
    - SPARK_CONF_spark_eventLog_dir=hdfs://namenode.hadoop:8020/spark-logs
    - SPARK_CONF_spark_history_fs_logDirectory=hdfs://namenode.hadoop:8020/spark-logs
    - SPARK_MASTER_URL=spark://spark-master.hadoop:7077
  env_file:
    - ./hadoop.env

spark-notebook:
  image: awesomedata/hadoop-spark-notebook
  hostname: sparknotebook
  container_name: sparknotebook
  domainname: hadoop
  net: hadoop
  environment:
    - SPARK_NOTEBOOK_MASTER=yarn-client  
  env_file:
    - ./hadoop.env    
  ports:
    - "9000:9000"

zookeeper:
  image: awesomedata/zookeeper
  hostname: zookeeper
  container_name: zookeeper
  domainname: hadoop
  net: hadoop
  ports:
    - "2181"

kafka1:
  image: awesomedata/kafka
  ports:
    - "9092"
  hostname: kafka1
  container_name: kafka1
  domainname: hadoop
  net: hadoop
  env_file:
        - ./kafka.env

kafka2:
  image: awesomedata/kafka
  ports:
    - "9092"
  hostname: kafka2
  container_name: kafka2
  domainname: hadoop
  net: hadoop
  env_file:
        - ./kafka.env

kafka3:
  image: awesomedata/kafka
  ports:
    - "9092"
  hostname: kafka3
  container_name: kafka3
  domainname: hadoop
  net: hadoop
  env_file:
        - ./kafka.env
